[package]
name = "rust-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
actix-cors = "0.6.4"
actix-web = "4.3"
anyhow = "1.0"
dotenv = "0.15"
env_logger = "0.10.0"
log = "0.4.19"
